/*------------------------------------------------------------------------
    File        : ILogger
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Mon Dec 06 12:17:07 EST 2010
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

interface OpenEdge.Core.Logger.ILogger:  
  
end interface.