/*------------------------------------------------------------------------
    File        : ISerializable
    Purpose     : Serializes an object 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Wed Jul 29 14:22:12 EDT 2009
    Notes       : 
  ----------------------------------------------------------------------*/
interface OpenEdge.Core.Util.ISerializable :
    
end interface.