object WizardForm: TISCustomForm
  Left = 0
  Top = 0
  Width = 413
  Height = 237
  DesignPanel = frmISWizardPage.elDesignPanel
  object lblDBAutoEdgeFactory: TLabel
    Left = 35
    Top = 28
    Width = 106
    Height = 13
    Caption = 'AutoEdge|TheFactory'
  end
  object txtDBAutoEdgeFactory: TEdit
    Left = 176
    Top = 24
    Width = 65
    Height = 21
    TabOrder = 0
    Text = '7010'
  end
end
