/*------------------------------------------------------------------------
    File        : ICondition
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Thu Mar 04 10:53:22 EST 2010
    Notes       : 
  ----------------------------------------------------------------------*/

interface OpenEdge.Core.InjectABL.Binding.Conditions.ICondition:
    
end interface.