/*------------------------------------------------------------------------
    File        : S0
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Fri Nov 20 10:44:33 EST 2009
    Notes       : 
  ----------------------------------------------------------------------*/
routine-level on error undo, throw.

using OpenEdge.Core.System.*.
using OpenEdge.Core.Util.*.
using Progress.Lang.*.

class OpenEdge.Test.S0 implements ISerializable: 

    
    method public void ReadObject( input po as ObjectInputStream ):

    end method.


 
    
    method public void WriteObject( input po as ObjectOutputStream ):

    end method.


 
end class.
