/*------------------------------------------------------------------------
    File        : ICloneable
    Purpose     : 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Fri Jan 15 14:35:27 EST 2010
    Notes       : 
  ----------------------------------------------------------------------*/
using Progress.Lang.*.

interface OpenEdge.Lang.ICloneable:  
  
end interface.
