/** ------------------------------------------------------------------------
    File        : IDefineResponse
    Purpose     : 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Tue Apr 27 09:21:34 EDT 2010
    Notes       : * Corresponds with OpenEdge.CommonInfrastructure.ServiceMessage.ServiceMessageActionEnum:Define
  ---------------------------------------------------------------------- */

interface OpenEdge.CommonInfrastructure.ServiceMessage.IDefineResponse  /* inherits IServiceResponse */:  
  
end interface.