/*------------------------------------------------------------------------
    File        : IDefineResponse
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Tue Apr 27 09:21:34 EDT 2010
    Notes       : * Corresponds with OpenEdge.Core.System.ServiceMessageActionEnum:Define
  ----------------------------------------------------------------------*/

interface OpenEdge.CommonInfrastructure.ServiceMessage.IDefineResponse  /* inherits IServiceMessage */:  
  
end interface.