/*------------------------------------------------------------------------
    File        : ISaveResponse
    Purpose     : Interface for data save response  
    Syntax      : 
    Description : 
    @author hdaniels
    Created     : Tue Feb 09 14:28:13 EST 2010
    Notes       : * Corresponds with OpenEdge.CommonInfrastructure.ServiceMessage.ServiceMessageActionEnum:Save
  ----------------------------------------------------------------------*/
interface OpenEdge.CommonInfrastructure.ServiceMessage.ISaveResponse: /* inherits IServiceMessage */

end interface.