/*------------------------------------------------------------------------
    File        : ISaveRequest
    Purpose     : Interface for data save request  
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : Tue Feb 09 14:28:13 EST 2010
    Notes       : * Corresponds with OpenEdge.Core.System.ServiceMessageActionEnum:Save
  ----------------------------------------------------------------------*/

interface OpenEdge.CommonInfrastructure.ServiceMessage.ISaveRequest /* inherits IServiceMessage */:      
end interface.