/*------------------------------------------------------------------------
    File        : ITableOwner
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Tue Aug 04 11:28:51 EDT 2009
    Notes       : 
  ----------------------------------------------------------------------*/
interface OpenEdge.Core.System.ITableOwner:
    
    method public handle GetTableHandle (pcTableName as character).
    
end interface.
