/** ------------------------------------------------------------------------
    File        : QueryElement
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Fri Dec 10 10:54:16 EST 2010
    Notes       : 
  ----------------------------------------------------------------------*/
{routinelevel.i}

class OpenEdge.Core.System.QueryElement abstract: 

end class.