/*------------------------------------------------------------------------
    File        : IApplicationStart
    Purpose     : Indicates that this is the first/main service to run in 
                  the application. This should be mapped to a concrete type
                  using InjectABL or some other scheme. 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Thu Apr 08 09:32:25 EDT 2010
    Notes       : 
  ----------------------------------------------------------------------*/

interface OpenEdge.CommonInfrastructure.Common.IApplicationStart: 
  
end interface.