/*------------------------------------------------------------------------
    File        : IManager
    Purpose     : 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Tue Apr 06 11:45:19 EDT 2010
    Notes       : 
  ----------------------------------------------------------------------*/
using OpenEdge.CommonInfrastructure.Common.IManager.
using OpenEdge.CommonInfrastructure.Common.IComponent.

interface OpenEdge.CommonInfrastructure.Common.IManager:    /* inherits IComponent */

    method public void ResetManager().
      
end interface.