/*------------------------------------------------------------------------
    File        : ISecurityManager
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Thu Mar 18 11:53:52 EDT 2010
    Notes       : 
  ----------------------------------------------------------------------*/
interface OpenEdge.CommonInfrastructure.Common.ISecurityManager:  
  
end interface.