/** ------------------------------------------------------------------------
    File        : IManager
    Purpose     : Common Manager interface - simple used for identifying services as managers. 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Tue Apr 06 11:45:19 EDT 2010
    Notes       : 
  ---------------------------------------------------------------------- */
using OpenEdge.CommonInfrastructure.Common.IManager.

interface OpenEdge.CommonInfrastructure.Common.IManager:    /* inherits IService */

end interface.