/*------------------------------------------------------------------------
    File        : IWorkflowRequest
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Wed Dec 01 19:05:07 EST 2010
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

interface OpenEdge.CommonInfrastructure.Common.ServiceMessage.IWorkflowRequest:  
  
end interface.