/** ------------------------------------------------------------------------
    File        : IWorkflowResponse
    Purpose     : A workflow service message response 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Wed Dec 01 19:05:15 EST 2010
    Notes       : 
  ---------------------------------------------------------------------- */
using OpenEdge.CommonInfrastructure.Common.ServiceMessage.IServiceResponse.

interface OpenEdge.CommonInfrastructure.Common.ServiceMessage.IWorkflowResponse inherits IServiceResponse:  

end interface.