/*------------------------------------------------------------------------
    File        : IWorkflowRequest
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Wed Dec 01 19:05:07 EST 2010
    Notes       : 
  ----------------------------------------------------------------------*/
using OpenEdge.CommonInfrastructure.Common.ServiceMessage.IServiceRequest.

interface OpenEdge.CommonInfrastructure.Common.ServiceMessage.IWorkflowRequest inherits IServiceRequest:  
  
end interface.