/*------------------------------------------------------------------------
    File        : IComponentContainer
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Mon Aug 31 10:15:57 EDT 2009
    Notes       :  
  ----------------------------------------------------------------------*/
using OpenEdge.PresentationLayer.View.*.

interface OpenEdge.PresentationLayer.View.IComponentContainer:

    method public IContainedView extent GetContainedViewComponents().
    
end interface.