/*------------------------------------------------------------------------
    File        : ILoginView
    Purpose     : 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Mon Apr 12 14:28:40 EDT 2010
    Notes       : 
  ----------------------------------------------------------------------*/
using Progress.Lang.*.

interface OpenEdge.PresentationLayer.View.ILoginView:
  
end interface.