/*------------------------------------------------------------------------
    File        : IDatasetModel
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Wed May 27 15:22:57 EDT 2009
    Notes       : 
  ----------------------------------------------------------------------*/

interface OpenEdge.PresentationLayer.Model.IDatasetModel /* inherits IModel */:
              
end interface.