/** ------------------------------------------------------------------------
    File        : QueryHeader
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Fri Dec 10 13:05:12 EST 2010
    Notes       : 
  ---------------------------------------------------------------------- */
routine-level on error undo, throw.

class OpenEdge.Core.System.QueryHeader: 

end class.