object WizardForm: TISCustomForm
  Left = 0
  Top = 0
  Width = 413
  Height = 237
  DesignPanel = frmISWizardPage.elDesignPanel
  object lblOpenEdgeRelease: TLabel
    Left = 18
    Top = 27
    Width = 91
    Height = 13
    Caption = 'OpenEdge Release'
  end
  object cbOpenEdgeRelease: TComboBox
    Left = 128
    Top = 24
    Width = 249
    Height = 21
    ItemHeight = 13
    TabOrder = 0
  end
end
