/** ------------------------------------------------------------------------
    File        : Queue
    Purpose     : 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Thu Oct 21 09:11:48 EDT 2010
    Notes       : 
  ---------------------------------------------------------------------- */

using Progress.Lang.*.

routine-level on error undo, throw.

class OpenEdge.Lang.Collections.Queue abstract: 

end class.