/*------------------------------------------------------------------------
    File        : ABLPrimitive
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Mon Oct 05 15:38:21 EDT 2009
    Notes       : 
  ----------------------------------------------------------------------*/
routine-level on error undo, throw.

class OpenEdge.Lang.ABLPrimitive abstract: 
    
end class.