/*------------------------------------------------------------------------
    File        : IApplicationLogin
    Purpose     : Common interface that indicates to the Service (and other)
                  managers that the implementing class is the login service. 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Wed Apr 14 16:04:27 EDT 2010
    Notes       : 
  ----------------------------------------------------------------------*/
interface OpenEdge.CommonInfrastructure.Common.IApplicationLogin:  
      
end interface.