/*------------------------------------------------------------------------
    File        : IModelReadOnly
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Tue Mar 17 17:02:39 EDT 2009
    Notes       : 
  ----------------------------------------------------------------------*/

interface OpenEdge.PresentationLayer.Model.IModelReadOnly:

end interface.
