/*------------------------------------------------------------------------
    File        : ISerializable
    Purpose     : Serializes to and from LONGCHAR. 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Wed Jul 29 14:22:12 EDT 2009
    Notes       : 
  ----------------------------------------------------------------------*/
  
interface OpenEdge.Core.Util.ISerializable :
    
end interface.