/*------------------------------------------------------------------------
    File        : IDefineRequest
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Tue Apr 27 09:20:27 EDT 2010
    Notes       : * Corresponds with OpenEdge.CommonInfrastructure.ServiceMessage.ServiceMessageActionEnum:Define
  ----------------------------------------------------------------------*/

interface OpenEdge.CommonInfrastructure.ServiceMessage.IDefineRequest /* inherits IServiceMessage */:  
  
end interface.