/** ------------------------------------------------------------------------
    File        : IWorkflowResponse
    Purpose     : A workflow service message response 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Wed Dec 01 19:05:15 EST 2010
    Notes       : 
  ---------------------------------------------------------------------- */
using OpenEdge.CommonInfrastructure.ServiceMessage.IWorkflowResponse.
using OpenEdge.Lang.Collections.ICollection.

interface OpenEdge.CommonInfrastructure.ServiceMessage.IWorkflowResponse:  

end interface.