@deprecated.
/*------------------------------------------------------------------------
    File        : ISharedModel
    Purpose     : 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Mon Jun 22 11:17:18 EDT 2009
    Notes       : 
  ----------------------------------------------------------------------*/

interface OpenEdge.PresentationLayer.Model.ISharedModel:  
  
end interface.